### ISSUE TITLE
android release not work

### ISSUE THREAD

**Issue by tqnie** [Magints-Technology-Solutions/payfort#8]
i can't pay this pakege on apk release how fixed this bugs

**Comment by devAhmadHamdy** [comment]
Hello @tqnie 
Make sure you are generating SDK token for release version and passing release choice in mode which is 1
Thank you

**Comment by tqnie** [comment]
i get Sdk token and change mode to  1 
but function method performPaymentRequest return null

thank you for repleay

**Comment by tqnie** [comment]
> 
> 
> Hello @tqnie Make sure you are generating SDK token for release version and passing release choice in mode which is 1 Thank you

i get Sdk token and change mode to 1
but function method performPaymentRequest return null

thank you for repleay

**Comment by devAhmadHamdy** [comment]
SDK token must be generated for release not for debug.
also show me the response you get.

**Comment by tqnie** [comment]
> 
I don't have any response because it's empty but it works on iphone release

**Comment by syrakozz** [comment]
im getting this 
/? E/MethodChannel#payfort_plugin: Failed to handle method call
    java.lang.NullPointerException
        at e.a.a.a.b.G()
        at h.a.c.a.j$a.a()
        at io.flutter.embedding.engine.f.c.h()
        at io.flutter.embedding.engine.f.c.i()
        at io.flutter.embedding.engine.f.c.j()
        at io.flutter.embedding.engine.f.a.run()
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
2022-01-11 09:29:05.920 14928-14954/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
        at e.a.a.a.b.G()
        at h.a.c.a.j$a.a()
        at io.flutter.embedding.engine.f.c.h()
        at io.flutter.embedding.engine.f.c.i()
        at io.flutter.embedding.engine.f.c.j()
        at io.flutter.embedding.engine.f.a.run()
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
    )
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
    <asynchronous suspension>
    #2      PayfortPlugin.performPaymentRequest (package:payfort_plugin/payfort_plugin.dart:28)
    <asynchronous suspension>
